server:
  port: 8080


spring:
#  config:
#    activate:
#      activate:
#        on-profile: local
  redis:
    host: localhost
    port: 6379

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/ordersystem
    username: root
    password: 1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
logging:
  level:
    root: info
jwt:
  expiration: 1
  secretKey: my_token_secret
  expirationRt: 14400
  secretKeyRt: hackerton_secret

  #aws s3설정 -> 실행할때 에러남
cloud:
  aws:
    credentials:
      access-key : test
      secret-key : test
    region:
      static: ap-northeast-2
    s3:
      bucket: hannahbucket21
